openapi: 3.1.0
info:
  version: 0.1.0
  title: Joby.ai API Reference
  termsOfService: https://blog.joby.ai/terms
  contact:
    email: hello@joby.ai
    url: https://www.joby.ai
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  summary: An API for searching jobs in the Joby.ai database.
  description: |
    Joby’s goal is to be the best job search engine on the planet, it scrapes the entire internet for every job on the internet and aggregates it in one place for the convenience of the job seeker.

    If you are interested in our API, please fill out [this short questionnaire](https://docs.google.com/forms/d/e/1FAIpQLScKJk7VrPv0TVPlOocXvpfxr1GIxifORhSWmj3jeTdqT6RbQQ/viewform) or contact us at [hello@joby.ai](mailto:hello@joby.ai) and we'll be in touch.
servers:
  - url: https://www.joby.ai/api/v0
security:
  - ApiKey: []
paths:
  /jobs:
    $ref: paths/jobs.yaml
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-api-key
      in: header
